### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dheimgartner** [dheimgartner/responseRateAnalysis#1]
- [x] Revise based on comments
- [x] Write response letter
- [x] `devtools::check()` and silence warnings, notes
- [x] Patch
- [x] Resubmit
- [x] Create branch
